version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: posttech2023
      MONGO_INITDB_DATABASE: fastfood
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: posttech2023
      ME_CONFIG_MONGODB_URL: mongodb://admin:posttech2023@mongo:27017
  web:
    container_name: web
    restart: always
    build: .
    environment:
      PORT: "3000"
      MONGO_URI: mongodb://admin:posttech2023@mongo:27017
    ports:
      - 3000:3000
    depends_on:
      - mongo
  

volumes:
  mongo-data: