apiVersion: v1
kind: Service
metadata:
  name: svc-tech-challenge
spec:
  selector:
    app: tech-challenge-app
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30100