apiVersion: v1
kind: Service
metadata:
  name: mongodb-pod-svc
spec:
  selector:
    app: mongodb-pod
  type: ClusterIP
  ports:
    - port: 80 
      protocol: TCP
    
      # porta que o Service irá se comunicar para despachar
      targetPort: 27017
    