name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  BUILD_IMAGE_ECR:
    uses: ./.github/workflows/image_ecr.yml
    secrets: inherit

  Deploy_EKS:
     uses: ./.github/workflows/tf-eks.yml
     secrets: inherit
     needs: BUILD_IMAGE_ECR
